resources:
  - ../../base
patchesStrategicMerge:
  - database-connection-sealed-secret.yaml
  - mapping.yaml
images:
  - name: greenstand/treetracker-grower-account-query
    newTag: 1.2.7
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization