---
apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  name: treetracker-grower-account-query
spec:
  cors:
    cors:
    origins:
    - '*'
    headers:
    - Content-Type
    - Authorization
    methods:
    - 'GET, POST, PATCH, PUT, OPTIONS, DELETE'
