apiVersion: apps/v1
kind: Deployment
metadata:
  name: treetracker-grower-account-query
  labels:
    app: treetracker-grower-account-query 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: treetracker-grower-account-query
  template:
    metadata:
      labels:
        app: treetracker-grower-account-query
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: doks.digitalocean.com/node-pool
                operator: In
                values:
                - microservices-node-pool
      containers:
      - name: treetracker-grower-account-query
        image: greenstand/treetracker-grower-account-query:TAG
        ports:
        - containerPort: 80
        env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: database-connection
                key: db
          - name: DATABASE_SCHEMA
            value: query
