apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: greenstand-docker-secret
  namespace: query
spec:
  encryptedData:
    '.dockerconfigjson': sealedSecret
  template:
    metadata:
      name: greenstand-docker-secret
      namespace: query
    type: kubernetes.io/dockerconfigjson
